### ISSUE TITLE
Block manager injections

### ISSUE THREAD

**Issue by sagikazarmark** [sonata-project/SonataBlockBundle#225] opened 2015-09-28 21:29 UTC
In many cases Blocks in feature bundles accept the general manager interface to be injected. For example:

``` php
use Sonata\CoreBundle\Model\ManagerInterface;

class RecentPostsBlockService extends BaseBlockService
{
    public function __construct($name, EngineInterface $templating, ManagerInterface $manager, Pool $adminPool = null)

```

Shouldn't these blocks accept the specific manager interface instead? In this case: `Sonata\NewsBundle\Model\PostManagerInterface`?

Since this interface extends the core manager interface it can simply be passed to the parent constructor.

Changing these signatures is a BC break, however this is unintended behaviour IMO, so it should not be a problem.

**Comment by sagikazarmark** [comment] 2015-09-28 21:30
Actually, the manager is not passed to the parent constructor.

**Comment by core23** [comment] 2016-05-16 17:14
👍 We should use the specific interfaces if we use their methods, not the general `ManagerInterface`

Feel free to create the missing PRs @sagikazarmark

**Comment by sagikazarmark** [comment] 2016-05-16 21:02
Will do.

**Comment by OskarStark** [comment] 2016-05-17 07:32
> Changing these signatures is a BC break, however this is unintended behaviour IMO, so it should not be a problem.

i think we can handle this BC by checking the injected interfaces manually and and deprecate the `ManagerInterface` here. In the next Major we could remove the manual check and add the type hint back.

What do you think @Soullivaneuh

**Comment by sagikazarmark** [comment] 2016-05-17 08:26
It depends: if you intend to release a major version soon, then I would say it is better to create a legacy branch (2.x) and break BC in master.

**Comment by jordisala1991** [comment] 2018-03-18 22:05
Atleast for the news-bundle and page-bundle (the first one because of this issue, and the second because I wanted to check another) are using specific interfaces or atleast moving there.

https://github.com/sonata-project/SonataNewsBundle/pull/265

This PR added that for news. On next major that will be the type-hint. 

Closing because the issue is just to general. If you have more cases using the general interface, please open a new issue there.

**Closed by jordisala1991** 2018-03-18 22:05 UTC
